name: GuicedEE Parent Module
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
jobs:
  ParentBOM:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: ''
      name: 'GuicedEE Parent POM'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit