name: GuicedEE Parent Module
on:
  workflow_dispatch:
    inputs:
      centralRelease:
        type: boolean
        description: Run a release to maven central
        default: false
  push:
env:
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

permissions:
  contents: write
  packages: write

jobs:
  ParentBOM:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: ''
      name: 'GuicedEE Parent POM'
      publishToCentral: ${{inputs.centralRelease}}
    secrets: inherit