name: Maven Package (BOM)
on:
  workflow_dispatch:
  push:
jobs:
  ParentBOM:
    uses: GuicedEE/Workflows/.github/workflows/bom.yml@master
    with:
      baseDir: ''
      name: 'GuicedEE Parent POM'
      publishToCentral: true
    secrets:
      USERNAME: ${{secrets.USERNAME}}
      USER_TOKEN: ${{secrets.USER_TOKEN}}
      SONA_USERNAME: ${{secrets.SONA_USERNAME}}
      SONA_PASSWORD: ${{secrets.SONA_PASSWORD}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}